thin-edge/tedge-rugpi-image

.github/workflows/bake-image.yml
README.md
recipes/rugpi-auto-rollback/files/healthcheck.sh
recipes/set-hostname-from-serial/files/set-hostname.sh
recipes/set-hostname-from-serial/files/startup-hostname.service
recipes/set-hostname-from-serial/recipe.toml
recipes/set-hostname-from-serial/steps/00-install.sh
recipes/thin-edge.io/steps/00-install.sh
rugpi-bakery.toml

Changes:
* set hostname from hardware information (e.g. serial number)
* update to latest thin-edge.io and use latest MQTT v1 api

chore: update thin-edge.io version

---

README.md
recipes/pi-cleanup-fix/recipe.toml
recipes/pi-cleanup-fix/steps/00-install.sh
recipes/thin-edge.io/steps/00-install.sh
rugpi-bakery.toml

override pi-cleanup recipe with custom to fix an issue with disabling a non existent service

override pi-cleanup recipe

---

recipes/rugpi-auto-rollback/files/healthcheck.sh
recipes/rugpi-auto-rollback/files/rugpi-auto-rollback.service

healtcheck logger improvements to make it easier to debug across failed firmware updates
* include timestamp in log entries
* log rotate (keeping only last 200 lines)

Improve healthcheck logger by adding timestamp prefixes

---

recipes/rugpi-auto-rollback/files/healthcheck.sh
recipes/thin-edge.io/steps/00-install.sh

Add new [tedge-inventory-plugin](https://github.com/thin-edge/tedge-inventory-plugin) which publishes information about the hardware and operating system on startup

feat: include tedge-inventory-plugin in image

---

.gitignore
recipes/mosquitto/steps/00-install.sh
recipes/thin-edge.io/steps/00-install.sh

Fix build issue caused by dpkg failing to override an existing configuration file. Now the dpkg preference is set when installing apt packages to use the new configuration files by default.
This should make the builds more reliable.

fix: override any existing configuration during apt installation

---

recipes/tedge-firmware-update/files/firmware-version

Add workaround for the issue: https://github.com/thin-edge/thin-edge.io/issues/2497

feat: add timestamp to firmware version inventory script

---

recipes/thin-edge.io/steps/00-install.sh

Fix a typo which led to the Raspberry Pi 1 and Zero images with incorrect thin-edge.io targets being installed (arm64 instead of armv6)

fix armv7 detection during image build

---

justfile

If the version included a full-stop, it was being omitted.

fix build info marker file in the image

---

justfile
scripts/c8y-publish-release.sh

Publish script to create firmware/versions in Cumulocity IoT using the external github url to the release page

build: support publishing to Cumulocity using artifacts hosted in github release

---

recipes/thin-edge.io/files/tedge-config.toml

Keep edits to the /etc/hosts as it contains host specific information

fix: persist etc hosts file

---

recipes/tedge-bootstrap/files/tedge-bootstrap

Set device.type on bootstrapping to the value returned by the c8y_Firmware inventory script. This prevents users from accidentally applying the wrong base image to the wrong device.

feat: set device.type on bootstrapping

---

.github/workflows/cd.yml

Add continuous deployment workflow to create the Cumulocity firmware artifacts in Cumulocity on a release

ci: publish release artifacts to c8y firmware repo

---

recipes/tedge-firmware-update/files/firware_update.rugpi.toml

Minor fixes to the firmware_update workflow.
* Transition to commit rather than successful after verification
* Fix syntax error on the `rollback_restart` state to use the `action` rather than the `script` property

fix(firmware): workflow fixes on commit and rollback

---

recipes/tedge-firmware-update/files/rugpi_workflow.sh

Fix the event text after commiting a new default partition by refreshing the state before publishing the event.

fix(firmware): refresh the default partition from rugpi before publishing the event to the user

---

recipes/tedge-bootstrap/files/tedge-bootstrap

Use explict tmp file when replacing the hostname in the /etc/hosts file rather than doing an in-place edit.
Related issue: https://github.com/thin-edge/tedge-rugpi-image/issues/42

fix: update hostname by using tmp file

---

recipes/tedge-bootstrap/files/tedge-bootstrap
recipes/tedge-firmware-update/steps/00-install.sh

publish firmware information to `/twin/firmware` topic (instead of c8y specific `/twin/c8y_Firmware`)

chore: publish firmware info on generic twin topic

---

recipes/tedge-bootstrap/files/tedge-identity

Detect Raspberry Pi Compute Modules and use the following device-id prefixes:
* Compute Module 3 => rpicm3
* Compute Module 3 => rpicm4

feat: detect rpi compute modules 3 and 4

---

recipes/tedge-bootstrap/files/tedge-identity

Resolve shellcheck warnings by grepping file directly rather than using cat.

fix(identity): resolve shellcheck warnings

---

recipes/thin-edge.io/files/tedge-configuration-plugin.toml
recipes/thin-edge.io/steps/00-install.sh

Include sensible default configuration files for:
* tedge-log-plugin.toml
* tedge-configuration-plugin.toml
The configuration files include default settings based on the other features offered by the image.

feat: add default log and configuration plugin settings

---

recipes/mosquitto/steps/00-install.sh

mosquitto is now installed using the bookworm-backport APT repository rather than sid. The backports repo is also left configured to easy updating the version at runtime

feat: install mosquitto from bookworm backports repo instead of sid

---

recipes/set-wifi/recipe.toml
recipes/set-wifi/steps/00-install.sh

The `set-wifi` receipe now support setting the `id` field of the NetworkManager wifi connection (before it was set to a fixed string).

fix(set-wifi): support setting network connection id via recipe

---

justfile

Update the base RaspberryPi OS version from `2023-10-10` to `2023-12-11`

feat: update base RaspberryPi OS image to version 2023-12-11

---

justfile

Avoid warning message when installing binfmt by install all formats.
Previously when running `just setup`, the following error would appear to users when they are running from an arm64 host (e.g. MacOS m*)
```
installing: arm64 cannot register "/usr/bin/qemu-aarch64" to /proc/sys/fs/binfmt_misc/register: write /proc/sys/fs/binfmt_misc/register: no such file or directory
```

fix: avoid warning message when installing binfmt by install all formats

---

scripts/compress.sh

Improve build process by automatically detecting when to use sudo when running `just bake`.
This is required as on some setups (e.g. linux), the `.img` file produced is owned by root and not the host user which then causes a problem when compressing the image.

fix(build): auto detection when to use when compressing the image using xz

---

recipes/docker/00-install.sh
recipes/docker/recipe.toml

This recipe will install Docker to the pi images. It will install after ThinEdge and add the tedge user the the docker group.

Add docker recipe

---

justfile
run-bakery

Use fixed verison of rugpi-bakery to avoid pulling in new versions unexpectedly

chore: use fixed rugpi version

---

recipes/docker/steps/00-install.sh

Install tedge-container-plugin which is a thin-edge.io software management plugin to list, install, remove container and container groups (e.g. docker compose projects).

feat(docker): install tedge-container-plugin in recipe

---

README.md

Add missing step to direct the user to install the dependencies required to build images of different architectures other than the user's host machine's architecture.

docs: add setup dependencies step

---

.github/workflows/bake-image.yml

Fix bug where the images were not included in the release artifacts due to the glob not being wide enough.

ci: fix publishing of release artifacts

---

rugpi-bakery.toml

The `include_firmware` option still needs to be set to `none` to prevent the firmware update for Pi 4 to be included. This was an oversight of mine. In the future, `none` will become the default.

fix: do not include firmware in `tryboot` images

---

.github/workflows/bake-image.yml

Add the `u-boot-containers` image to the CI workflow.

build: include u-boot-containers image in workflow

---

layers/containers.toml
recipes/tedge-config/recipe.toml
recipes/tedge-config/steps/00-install.sh

Add new recipe to set the thin-edge.io MQTT bind address so the MQTT broker accepts incoming connections from the docker network

feat(containers): set mqtt bind address to make broker accessible from containers

---

.github/workflows/bake-image.yml
.github/workflows/cd.yml

Install just using snap rather than relying on the github action as the action depends on the now deprecated nodejs v16.

ci: replace just action with snap installer

---

.github/workflows/bake-image.yml
.github/workflows/cd.yml

Reverts thin-edge/tedge-rugpi-image#72 as the version of just in the snapstore is very old (1.2.0 vs 1.22.0!)

Revert "ci: replace just action with snap installer"

---

.github/workflows/bake-image.yml
.github/workflows/cd.yml

Switch action which installs just (the task runner) to avoid nodejs 16 deprecation warnings.

ci: update just actions to avoid nodejs 16 deprecation notices

---

README.md
rugpi-bakery.toml

Add new image for armhf builds which includes docker pre-installed.
You can build the image using:
```sh
just IMAGE=u-boot-armhf-containers build
```

feat(armhf): add armhf image with docker preinstalled

---

.gitconfig
run-bakery

Avoid an issue when building the image inside a docker container where git does not trust the project repository.

fix: mount gitconfig to avoid git permissions errors

---

README.md
env.template

Support installing thin-edge.io pre-releases (from the main channel) by setting an environment variable in the dotenv file, `.env`:
```sh
TEDGE_INSTALL_CHANNEL=main
```

feat: support installing thin-edge.io pre-releases

---

justfile

Added missing entries where the Raspberry Pi 2W device was not explicitly mentioned in the list of devices where an image was applicable to.
Now, when using the following task, pizero2w is included in the list:
```sh
$ just build-pizero2w
This image can be applied to
* pi2
* pi3
* pizero2w
```

docs: include pizero2 in the list of devices an image can be applied to

---

layers/debian-containers.toml
layers/rpi-containers.toml
layers/rpi-default.toml
rugpi-bakery.toml

Update layer to include
* Support for resolving mdns addresses using systemd-resolved (stub DNS server)
* [tedge-pki-smallstep](https://github.com/thin-edge/tedge-pki-smallstep) community plugin to provide a local PKI (though still a work in progress)
* Enable cgroups memory monitoring

feat: update layer to include new networking and local pki improvements

---

README.md

Fix the documentation which referenced an invalid `IMAGE=` name.

docs: fix build instructions when selecting an image
